SCHOLARSHIPS = [
    {
        "name": "Central Sector Scheme of Scholarships for College and University Students",
        "provider": "Department of Higher Education, Government of India",
        "scheme": "National Scholarship Portal",
        "eligibility": "For students pursuing regular undergraduate or postgraduate study with strong Class 12 performance.",
        "deadline": "Check current NSP schedule",
        "tags": "merit, central sector, undergraduate, postgraduate",
        "amount": "Up to Rs. 20,000 per year",
        "country": "India",
        "level": "Undergraduate / Postgraduate",
        "targetLevel": "under_grad",
        "eligibleEducationLevels": ["higher_secondary", "under_grad"],
        "eligibleCastes": [],
        "eligibleGenders": [],
        "eligibleReligions": [],
        "maxFamilyIncome": 800000,
        "minimumPercentage": 80,
        "applyLink": "https://scholarships.gov.in/"
    },
    {
        "name": "Post Matric Scholarship for SC Students",
        "provider": "Ministry of Social Justice and Empowerment",
        "scheme": "National Scholarship Portal",
        "eligibility": "For Scheduled Caste students studying in Class 11 and above with family income within scheme limits.",
        "deadline": "Check current NSP schedule",
        "tags": "SC, post matric, tuition support, maintenance allowance",
        "amount": "As per course and hosteller/day scholar norms",
        "country": "India",
        "level": "Class 11 to PhD",
        "targetLevel": "higher_secondary",
        "eligibleEducationLevels": ["higher_secondary", "under_grad"],
        "eligibleCastes": ["sc"],
        "eligibleGenders": [],
        "eligibleReligions": [],
        "maxFamilyIncome": 250000,
        "minimumPercentage": 50,
        "applyLink": "https://scholarships.gov.in/"
    },
    {
        "name": "Post Matric Scholarship for ST Students",
        "provider": "Ministry of Tribal Affairs",
        "scheme": "National Scholarship Portal",
        "eligibility": "For Scheduled Tribe students in post-matric study with family income within the prescribed ceiling.",
        "deadline": "Check current NSP schedule",
        "tags": "ST, tribal affairs, post matric, higher education",
        "amount": "As per approved scholarship components",
        "country": "India",
        "level": "Class 11 to PhD",
        "targetLevel": "higher_secondary",
        "eligibleEducationLevels": ["higher_secondary", "under_grad"],
        "eligibleCastes": ["st"],
        "eligibleGenders": [],
        "eligibleReligions": [],
        "maxFamilyIncome": 250000,
        "minimumPercentage": 50,
        "applyLink": "https://scholarships.gov.in/"
    },
    {
        "name": "Merit Cum Means Scholarship for Professional and Technical Courses",
        "provider": "Ministry of Minority Affairs",
        "scheme": "National Scholarship Portal",
        "eligibility": "For minority students pursuing professional or technical courses with at least 50 percent marks and limited family income.",
        "deadline": "Check current NSP schedule",
        "tags": "minority, merit cum means, technical, professional",
        "amount": "Course fee support plus maintenance allowance",
        "country": "India",
        "level": "Undergraduate / Postgraduate",
        "targetLevel": "under_grad",
        "eligibleEducationLevels": ["higher_secondary", "under_grad"],
        "eligibleCastes": [],
        "eligibleGenders": [],
        "eligibleReligions": ["muslim", "christian", "sikh", "buddhist", "jain", "parsi"],
        "maxFamilyIncome": 250000,
        "minimumPercentage": 50,
        "applyLink": "https://scholarships.gov.in/"
    },
    {
        "name": "Top Class Education Scheme for SC Students",
        "provider": "Ministry of Social Justice and Empowerment",
        "scheme": "National Scholarship Portal",
        "eligibility": "For Scheduled Caste students admitted to top institutions and meeting income criteria.",
        "deadline": "Check current NSP schedule",
        "tags": "SC, top class education, premier institutes",
        "amount": "Tuition fee, living expenses, books and computer allowance",
        "country": "India",
        "level": "Undergraduate / Postgraduate",
        "targetLevel": "under_grad",
        "eligibleEducationLevels": ["under_grad"],
        "eligibleCastes": ["sc"],
        "eligibleGenders": [],
        "eligibleReligions": [],
        "maxFamilyIncome": 800000,
        "minimumPercentage": 60,
        "applyLink": "https://scholarships.gov.in/"
    },
    {
        "name": "National Fellowship and Scholarship for Higher Education of ST Students",
        "provider": "Ministry of Tribal Affairs",
        "scheme": "National Scholarship Portal",
        "eligibility": "For ST students in identified higher education institutions with family income within eligible limits.",
        "deadline": "Check current NSP schedule",
        "tags": "ST, top class, higher education, tribal affairs",
        "amount": "Tuition fee support, living expenses and allowances",
        "country": "India",
        "level": "Undergraduate / Postgraduate",
        "targetLevel": "under_grad",
        "eligibleEducationLevels": ["under_grad"],
        "eligibleCastes": ["st"],
        "eligibleGenders": [],
        "eligibleReligions": [],
        "maxFamilyIncome": 600000,
        "minimumPercentage": 60,
        "applyLink": "https://scholarships.gov.in/"
    },
    {
        "name": "AICTE Pragati Scholarship for Girls",
        "provider": "AICTE",
        "scheme": "AICTE Scholarship Scheme",
        "eligibility": "For girl students admitted to diploma or degree technical courses with family income within the approved ceiling.",
        "deadline": "Check current AICTE schedule",
        "tags": "girls, AICTE, technical education, degree, diploma",
        "amount": "Rs. 50,000 per year",
        "country": "India",
        "level": "Technical Degree / Diploma",
        "targetLevel": "under_grad",
        "eligibleEducationLevels": ["higher_secondary", "under_grad"],
        "eligibleCastes": [],
        "eligibleGenders": ["female"],
        "eligibleReligions": [],
        "maxFamilyIncome": 800000,
        "minimumPercentage": 50,
        "applyLink": "https://www.aicte-india.org/"
    },
    {
        "name": "AICTE Saksham Scholarship",
        "provider": "AICTE",
        "scheme": "AICTE Scholarship Scheme",
        "eligibility": "For specially abled students admitted to technical degree or diploma programmes with eligible family income.",
        "deadline": "Check current AICTE schedule",
        "tags": "AICTE, disability, technical education, inclusive scholarship",
        "amount": "Rs. 50,000 per year",
        "country": "India",
        "level": "Technical Degree / Diploma",
        "targetLevel": "under_grad",
        "eligibleEducationLevels": ["higher_secondary", "under_grad"],
        "eligibleCastes": [],
        "eligibleGenders": [],
        "eligibleReligions": [],
        "maxFamilyIncome": 800000,
        "minimumPercentage": 50,
        "applyLink": "https://www.aicte-india.org/"
    },
    {
        "name": "Prime Minister's Scholarship Scheme",
        "provider": "WARB, Ministry of Home Affairs / RPF and related departments",
        "scheme": "PM Scholarship Scheme",
        "eligibility": "For dependent wards of ex-servicemen, ex-coast guard personnel, police personnel and certain service categories as notified.",
        "deadline": "Check current PMSS schedule",
        "tags": "PMSS, defence, police, dependents, professional courses",
        "amount": "As per current PMSS rates",
        "country": "India",
        "level": "Professional Degree",
        "targetLevel": "under_grad",
        "eligibleEducationLevels": ["higher_secondary", "under_grad"],
        "eligibleCastes": [],
        "eligibleGenders": [],
        "eligibleReligions": [],
        "maxFamilyIncome": None,
        "minimumPercentage": 60,
        "applyLink": "https://scholarships.gov.in/"
    },
    {
        "name": "Ishan Uday Special Scholarship Scheme for North Eastern Region",
        "provider": "UGC",
        "scheme": "UGC Scholarship Scheme",
        "eligibility": "For students from the North Eastern Region pursuing general or professional degree courses.",
        "deadline": "Check current UGC schedule",
        "tags": "UGC, north east, undergraduate, regional support",
        "amount": "Monthly scholarship as per UGC norms",
        "country": "India",
        "level": "Undergraduate",
        "targetLevel": "under_grad",
        "eligibleEducationLevels": ["higher_secondary", "under_grad"],
        "eligibleCastes": [],
        "eligibleGenders": [],
        "eligibleReligions": [],
        "maxFamilyIncome": 450000,
        "minimumPercentage": 50,
        "applyLink": "https://scholarships.gov.in/"
    },
    {
        "name": "National Means Cum Merit Scholarship",
        "provider": "Department of School Education and Literacy",
        "scheme": "National Scholarship Portal",
        "eligibility": "For meritorious students from economically weaker sections studying at the secondary level.",
        "deadline": "Check current NSP schedule",
        "tags": "school, merit, means, class 9 to 12",
        "amount": "As per NMMS norms",
        "country": "India",
        "level": "Secondary / Higher Secondary",
        "targetLevel": "higher_secondary",
        "eligibleEducationLevels": ["high_school", "higher_secondary"],
        "eligibleCastes": [],
        "eligibleGenders": [],
        "eligibleReligions": [],
        "maxFamilyIncome": 350000,
        "minimumPercentage": 55,
        "applyLink": "https://scholarships.gov.in/"
    }
]
